import os
import time
from datetime import date
import pyautogui
import requests
from webbot import Browser


def login():
    url = "https://www.naukri.com/nlogin/login"
    web.go_to(url)
    web.type(username, id="usernameField")
    web.type(password, id="passwordField")
    web.click('login')
    time.sleep(2)


def login_details():
    global username, password
    print("[+] Make sure your resume name must be all small letters as '(resume.pdf)'")
    with open("data.txt", "a+") as da:
        print("[+] Searching for username and password in data.txt")
        da.seek(0)
        file_data = da.read(1)
        if not file_data:
            print("[*] For first time usage to save login details in data.txt [*]")
            username = input("[+] Enter email or username :- ").strip()
            password = input("[+] Enter password :- ").strip()
            da.write(str(username) + '\n' + str(password))
        else:
            da.seek(0)
            print("[+] username and password loaded from data.txt")
            data = da.read().split('\n')
            username = data[0]
            password = data[1]


def internet_check():
    try:
        requests.get("https://google.com")
        main()
    except requests.ConnectionError:
        print("[-] no internet")

def resume_exist():
        if os.path.exists(os.path.join(os.getcwd(), 'resume.pdf')):
            print("[+] Resume file loaded")
        else:
            print("[-] please put your resume in the current folder and rename as (resume.pdf)")
            quit()


def main():
    global web
    login_details()
    resume_exist()
    web = Browser()
    login()
    if_login_true(web)


def close(web):
    print("[-] closing...")
    web.quit()


def if_login_true(web):
    login_status = web.exists(xpath="/html/body/div[1]/div/div/ul[2]/li[2]/div/ul[2]/li[5]/a")
    while login_status == False:
        login_status = web.exists(xpath="/html/body/div[1]/div/div/ul[2]/li[2]/div/ul[2]/li[5]/a")
    if login_status:
        resume_upload(web)


def resume_upload(web):
    web.go_to("https://www.naukri.com/mnjuser/profile?id=&altresid")
    resume = str(os.path.join(os.getcwd(), 'resume.pdf'))
    console_tool()
    time.sleep(2)
    resume_xpath = '/html/body/div[2]/div/div/span/div/div/div/div/div/div[2]/div[3]/div[2]/div/div/div[2]/div[2]/div/div[1]/div[1]/section/div/div[1]/input'
    script1 = f"document.evaluate ('{resume_xpath}', document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue.click();"
    pyautogui.write(script1)
    pyautogui.press('enter')
    time.sleep(2)
    pyautogui.write(resume)
    time.sleep(2)
    pyautogui.press('enter')
    time.sleep(2)
    console_tool()
    resume_update_check(web)


def resume_update_check(web):
    time.sleep(2)
    today = date.today()
    today_date = 'Uploaded on '+today.strftime("%b %d, %Y")
    resume_date = web.find_elements(xpath='/html/body/div[2]/div/div/span/div/div/div/div/div/div[2]/div[3]/div[2]/div/div/div[2]/div[1]/div[1]/div[1]/div/span')[0].text
    while resume_date != today_date:
        resume_date = web.find_elements(xpath='/html/body/div[2]/div/div/span/div/div/div/div/div/div[2]/div[3]/div[2]/div/div/div[2]/div[1]/div[1]/div[1]/div/span')[0].text
    if resume_date == today_date:
        print(f"[+] Taking screenshot as resume_updated_{resume_date}.png")
        web.get_screenshot_as_file(f"resume_updated_{resume_date}.png")
        print("[+] Resume updated successfully")
        close(web)
    else:
        print("[-] upload failed")


def console_tool():
    pyautogui.keyDown('ctrl')
    pyautogui.keyDown('shift')
    pyautogui.press('j')
    pyautogui.keyUp('ctrl')
    pyautogui.keyUp('shift')


def credit():
    print("""
               NAUKRI RESUME UPDATER""")
    print("""
 ██▀███   ▄▄▄       ██░ ██  █    ██  ██▓    
▓██ ▒ ██▒▒████▄    ▓██░ ██▒ ██  ▓██▒▓██▒    
▓██ ░▄█ ▒▒██  ▀█▄  ▒██▀▀██░▓██  ▒██░▒██░    
▒██▀▀█▄  ░██▄▄▄▄██ ░▓█ ░██ ▓▓█  ░██░▒██░    
░██▓ ▒██▒ ▓█   ▓██▒░▓█▒░██▓▒▒█████▓ ░██████▒
░ ▒▓ ░▒▓░ ▒▒   ▓▒█░ ▒ ░░▒░▒░▒▓▒ ▒ ▒ ░ ▒░▓  ░
  ░▒ ░ ▒░  ▒   ▒▒ ░ ▒ ░▒░ ░░░▒░ ░ ░ ░ ░ ▒  ░
  ░░   ░   ░   ▒    ░  ░░ ░ ░░░ ░ ░   ░ ░   
   ░           ░  ░ ░  ░  ░   ░         ░  ░ code generated by Rahul.p
""")



try:
    credit()
    internet_check()
except KeyboardInterrupt:
    print("\n[-] Exiting ....")
